CREATE TABLE IF NOT EXISTS  `department` (
  `MANAGER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEPARTMENT_NAME` varchar(255) NOT NULL,
  `MGR_FIRST_NAME` varchar(255) NOT NULL,
  `DEPARTMENT_ID` int(11) DEFAULT NULL,
  `MGR_LAST_NAME` varchar(255) NOT NULL,
  PRIMARY KEY (`MANAGER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=206 DEFAULT CHARSET=utf8mb4;